accumulate_grad_batches: 1
adam_b1: 0.8
adam_b2: 0.99
amp: false
audio_num_mel_bins: 80
audio_sample_rate: 22050
aux_context_window: 0
base_config:
- egs/egs_bases/tts/vocoder/hifigan.yaml
- ./base.yaml
binarization_args:
  reset_phone_dict: true
  reset_word_dict: true
  shuffle: true
  trim_eos_bos: false
  trim_sil: false
  with_align: false
  with_f0: true
  with_f0cwt: false
  with_linear: false
  with_spk_embed: false
  with_spk_id: true
  with_txt: false
  with_wav: true
  with_word: false
binarizer_cls: data_gen.tts.base_binarizer.BaseBinarizer
binary_data_dir: data/binary/hifitts_wav
# binary_data_dir: data/binary/hifitts_wav
check_val_every_n_epoch: 10
clip_grad_norm: 1
clip_grad_value: 0
debug: false
dec_ffn_kernel_size: 9
dec_layers: 4
dict_dir: ''
disc_start_steps: 40000
discriminator_grad_norm: 1
discriminator_optimizer_params:
  lr: 0.0002
discriminator_scheduler_params:
  gamma: 0.999
  step_size: 600
dropout: 0.1
ds_workers: 1
enc_ffn_kernel_size: 9
enc_layers: 4
endless_ds: true
ffn_act: gelu
ffn_padding: SAME
fft_size: 1024
fmax: 7600
fmin: 80
frames_multiple: 1
gen_dir_name: ''
generator_grad_norm: 10
generator_optimizer_params:
  lr: 0.0002
generator_scheduler_params:
  gamma: 0.999
  step_size: 600
griffin_lim_iters: 60
hidden_size: 256
hop_size: 256
infer: true
lambda_adv: 1.0
lambda_cdisc: 4.0
lambda_mel: 5.0
lambda_mel_adv: 1.0
load_ckpt: ''
loud_norm: false
lr: 2.0
max_epochs: 1000
max_frames: 1548
max_input_tokens: 1550
max_samples: 8192
max_sentences: 24
max_tokens: 30000
max_updates: 3000000
max_valid_sentences: 1
max_valid_tokens: 60000
mel_vmax: 1.5
mel_vmin: -6
min_frames: 0
min_level_db: -100
num_ckpt_keep: 3
num_heads: 2
num_mels: 80
num_sanity_val_steps: 5
num_spk: 50
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
out_wav_norm: false
pitch_extractor: parselmouth
pre_align_args:
  allow_no_txt: false
  denoise: false
  sox_resample: false
  sox_to_wav: true
  trim_sil: false
  txt_processor: en
  use_tone: true
pre_align_cls: egs.datasets.audio.hifitts.pre_align.HifiTTSPreAlign
print_nan_grads: false
processed_data_dir: data/processed/hifitts
profile_infer: false
raw_data_dir: data/raw/hifi-tts
ref_level_db: 20
rename_tmux: true
resblock: '1'
resblock_dilation_sizes:
- - 1
  - 3
  - 5
- - 1
  - 3
  - 5
- - 1
  - 3
  - 5
resblock_kernel_sizes:
- 3
- 7
- 11
resume_from_checkpoint: 0
save_best: true
save_codes: []
save_f0: false
save_gt: true
scheduler: rsqrt
seed: 1234
sort_by_len: true
task_cls: tasks.vocoder.hifigan.HifiGanTask
tb_log_interval: 100
test_input_dir: ''
test_num: 200
test_set_name: test
train_set_name: train
upsample_initial_channel: 512
upsample_kernel_sizes:
- 16
- 16
- 4
- 4
upsample_rates:
- 8
- 8
- 2
- 2
use_cdisc: false
use_cond_disc: false
use_fm_loss: false
use_ms_stft: false
use_pitch_embed: false
use_spec_disc: false
use_spk_id: true
val_check_interval: 2000
valid_infer_interval: 10000
valid_monitor_key: val_loss
valid_monitor_mode: min
valid_set_name: valid
vocoder: pwg
vocoder_ckpt: ''
warmup_updates: 8000
weight_decay: 0
win_length: null
win_size: 1024
window: hann
word_size: 30000
work_dir: checkpoints/0902_hifigan_hifitts_1
# ds_name: aishell3_vctk #talcs
# spk_emb_wav_fn: inference/audio_backup/陈杨-说话人验证任务.wav


# use_separate_encoder: false
# language_embedding_dimension: 32

# # knn edit
# knn:
#   repalce_all_spk: true
#   knn-edit: true
#   knn-edit-weight: 1
#   topk: 4
#   knn-edit-dataset: data/binary/talcs